# component: "@sls-next/serverless-component@latest"

# inputs:
#   domain:
#     - adultna.com
#   bucketName: "your-nextjs-bucket"
#   defaultLambda:
#     name: "next-default"
#   apiLambda:
#     name: "next-api"
#   imageLambda:
#     name: "next-image"
