name: CI

on:
  push:
    branches: [development, master]
  pull_request:
    branches: [development, master]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v2
        with:
          version: 10.15.0
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm
        run: pnpm install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: |
          if [ -f tsconfig.json ]; then
            npm run typecheck
          else
            echo "No tsconfig.json found, skipping type check"
          fi

      - name: Run tests
        run: |
          if [ -f jest.config.js ] || [ -d __tests__ ]; then
            npm test
          else
            echo "No tests found, skipping"
          fi

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_API: ${{ secrets.NEXT_PUBLIC_API }}
          NEXT_PUBLIC_JSEARCH_KEY: ${{ secrets.NEXT_PUBLIC_JSEARCH_KEY }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
