name: Playwright Tests
on:
  push:
    branches: [main, master, development]
  pull_request:
    branches: [main, master, development]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install pnpm
        run: |
          npm install -g pnpm
          export PNPM_HOME="$(npm bin -g)"
          echo "$PNPM_HOME" >> $GITHUB_PATH
          export PATH="$PNPM_HOME:$PATH"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
